apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: productsstoresonk8s-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   tier: frontend
   app: productsstoresonk8s
 template:
  metadata:
   name: frontend-pods
   labels:
    app: productsstoresonk8s
    tier: frontend
  spec: 
   containers:
   - image: haripraghash/productstoresonk8s:v4.#{Build.BuildId}#
     name: frontend-containers
     ports:
     - containerPort: 80
       protocol: TCP
     env:
     - name: ConnectionStrings__ProductsContext
       valueFrom:
         secretKeyRef:
          name: mssql-secret
          key: db-connection-string-secret