kind: Service
apiVersion: v1
metadata:
  name:  productsstoresonk8s-service
spec:
  selector:
    app:  productsstoresonk8s
    tier: frontend
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  80
    protocol: TCP