apiVersion: v1
kind: PersistentVolume
metadata:
 name: mssql-pv
 labels:
  app: prouctsstoresonk8s
spec:
 capacity:
  storage: 1Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
  path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mssql-pv-claim
 labels:
  app: productsstoresonk8s
spec:
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 1Gi
