apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  labels:
    app: productsstoresonk8s
data:
  db-connection-string: Server=mssql-service,1433;Database=ProductsDB;User=sa;Password=@Aa123456;
