apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  mssql-deployment
  labels:
    app:  productsstoresonk8s
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  productsstoresonk8s
        tier: backend
    spec:
      containers:
      - image:  microsoft/mssql-server-linux
        name:  mssql
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  ACCEPT_EULA
          value:  "Y"   
        - name: SA_PASSWORD
          value: "@Aa123456"    
        ports:
        - containerPort:  1433
          name:  mssql-port
        volumeMounts:
         - mountPath: /var/opt/mssql
           name: productsstoresonk8s-volume
      volumes:
      - name:  productsstoresonk8s-volume
        persistentVolumeClaim:
         claimName: mssql-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-service
spec:
  selector:
    app: productsstoresonk8s
    tier: backend
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 30801
